"""
Figure-8 / Torus knot creation using CadQuery.

Creates a figure-8 style knot by sweeping an LED circle cross-section
along a torus knot path generated by pyknotid.
"""

import logging
from cadquery.func import spline

logger = logging.getLogger(__name__)
from pyknotid.make import k8_21, torus_knot, periodic_knot
from pyknotid.visualise import plot_line, plot_line_vispy

from led_knots.core import draw_part, get_config, scale_pyknot_points

# Load configuration
config = get_config(
    name="Figure 8 Knot",
    description="Create and render a figure 8 knot"
)

k = torus_knot(p=5, q=10, num=150).points

# Scale the knot coordinates to fit within the bounding box
# Using width for x, width for y, and height for z (length)
knot_points = scale_pyknot_points(
    k,
    width=config.output_bounds.width,
    height=config.output_bounds.width,
    length=config.output_bounds.height,
    padding=config.tube_settings.outer_radius,
    preserve_aspect_ratio=False,
)

# Note: Currently when the path is closed, there is an error since faces overlap
# TODO: Fix closed path handling
path = spline(knot_points[:-1])

# Create, sweep, and render the part
draw_part(path, config, rotation_z=90)
