"""
Figure-8 / Torus knot creation using CadQuery.

Creates a figure-8 style knot by sweeping an LED circle cross-section
along a torus knot path generated by pyknotid.
"""

import logging

from cadquery.func import spline
from pyknotid.make import torus_knot

from led_knots.core import draw_part, scale_pyknot_points
from led_knots.core.config import Config

logger = logging.getLogger(__name__)


def build(config: Config) -> None:
    k = torus_knot(p=5, q=10, num=150).points

    knot_points = scale_pyknot_points(
        k,
        width=config.output_bounds.width,
        height=config.output_bounds.height,
        length=config.output_bounds.length,
        padding=config.tube_settings.outer_radius,
    )

    path = spline(knot_points[:-5])
    draw_part(path, config)
