"""
K8_21 knot creation using CadQuery.

Creates a k8_21 knot by sweeping an LED circle cross-section
along a mathematical k8_21 knot path generated by pyknotid.

Uses build_ribbon_aux_spine(path, config) to constrain twist from config
(min_90_degree_twist_distance) and align bends with the flexible axis.
"""

import logging

from cadquery.func import spline
import pyknotid.make as mk

from led_knots.core import (
    draw_part,
    get_config,
    build_ribbon_aux_spine,
    scale_pyknot_points,
)

logger = logging.getLogger(__name__)

config = get_config(name="K8_21 Knot", description="Create and render a k8_21 knot")

spine_offset_radius = 5.0

# Generate the k8_21 knot path using pyknotid, scaled to config output bounds.
# More points give a smoother path; 150 balances smoothness and build time.
k = mk.k8_21(num_points=300)
knot_points = scale_pyknot_points(
    k.points,
    width=config.output_bounds.width,
    height=config.output_bounds.width,
    length=config.output_bounds.height,
    padding=config.tube_settings.outer_radius,
    preserve_aspect_ratio=False
)

# Open path (closed path causes face overlap)
path = spline(knot_points[:-1])

# Raises ValueError if twist cannot be achieved within min_90_degree_twist_distance.
# Higher num_samples yields a smoother aux spine (150 balances smoothness and build time).
aux_spine, initial_rotation = build_ribbon_aux_spine(
    path,
    config,
    num_samples=150,
    spine_offset_radius=spine_offset_radius,
)

# Create, sweep, and render (draw_part supports --preview for image output)
draw_part(path, config, aux=aux_spine, rotation_z=initial_rotation)

