"""
Trefoil knot creation using CadQuery.

Creates a trefoil knot by sweeping an LED circle cross-section
along a mathematical trefoil knot path generated by pyknotid.

Uses build_ribbon_aux_spine(path, config) to constrain twist from config
(min_90_degree_twist_distance) and align bends with the flexible axis.
"""

import logging

from cadquery.func import spline
from pyknotid.make import trefoil as make_trefoil

from led_knots.core import (
    draw_part,
    build_ribbon_aux_spine,
    scale_pyknot_points,
)
from led_knots.core.config import Config

logger = logging.getLogger(__name__)


def build(config: Config) -> None:
    spine_offset_radius = 5.0

    k = make_trefoil(num_points=150)
    knot_points = scale_pyknot_points(
        k.points,
        width=config.output_bounds.width,
        height=config.output_bounds.height,
        length=config.output_bounds.length,
        padding=config.tube_settings.outer_radius,
    )

    path = spline(knot_points[:-1])

    aux_spine, initial_rotation = build_ribbon_aux_spine(
        path,
        config,
        num_samples=150,
        spine_offset_radius=spine_offset_radius,
    )

    draw_part(path, config, aux=aux_spine, rotation_z=initial_rotation)
