"""
Trefoil knot creation using CadQuery.

Creates a trefoil knot by sweeping an LED circle cross-section
along a mathematical trefoil knot path generated by pyknotid.

Uses build_ribbon_aux_spine(path, config) to constrain twist from config
(min_90_degree_twist_distance) and align bends with the flexible axis.
"""

import logging

from cadquery.func import spline
from pyknotid.make import trefoil as make_trefoil

from led_knots.core import (
    draw_part,
    get_config,
    build_ribbon_aux_spine,
    scale_pyknot_points,
)

logger = logging.getLogger(__name__)

config = get_config(
    name="Trefoil Knot",
    description="Create and render a trefoil knot",
)

spine_offset_radius = 5.0

# Generate the trefoil knot path using pyknotid, scaled to config output bounds
k = make_trefoil(num_points=100)
knot_coords = scale_pyknot_points(
    k.points,
    width=config.output_bounds.width,
    height=config.output_bounds.width,
    length=config.output_bounds.height,
)
knot_points = [(float(p[0]), float(p[1]), float(p[2])) for p in knot_coords]

# Open path (closed path causes face overlap)
path = spline(knot_points[:-1])

# Raises ValueError if twist cannot be achieved within min_90_degree_twist_distance
aux_spine, initial_rotation = build_ribbon_aux_spine(
    path,
    config,
    num_samples=100,
    spine_offset_radius=spine_offset_radius,
)

# Create, sweep, and render the part (draw_part uses path + aux + rotation_z)
draw_part(path, config, aux=aux_spine, rotation_z=initial_rotation)

