"""
Trefoil knot creation using CadQuery.

Creates a trefoil knot by sweeping an LED circle cross-section
along a mathematical trefoil knot path generated by pyknotid.
"""

import logging
from cadquery.func import *
from pyknotid.make import trefoil as make_trefoil

from led_knots.core import parse_args, render_part, scale_pyknot_points
from led_knots.core import create_led_circle_face


def main():
    """Generate and render the trefoil knot."""
    logging.basicConfig(level=logging.DEBUG)

    tube_radius = 15
    height = 100.0                    # Height of the pipe (mm)
    width = 175.0
    wall_thickness = 1.0             # Wall thickness (mm)
    oval_wall_thickness = 2.0

    args = parse_args(description="Create and render a trefoil knot")

    # Generate the trefoil knot path using pyknotid
    # This creates a mathematical trefoil knot curve
    k = make_trefoil(num_points=50)

    # Scale the knot coordinates to fit within the bounding box
    # Using width for x, width for y, and height for z (length)
    knot_coords = scale_pyknot_points(k.points, width=width, height=width, length=height)

    # Convert numpy array to list of 3D points for CadQuery
    # pyknotid returns points as (x, y, z) coordinates
    knot_points = []
    for point in knot_coords:
        knot_points.append((float(point[0]), float(point[1]), float(point[2])))

    # Note: Currently when the path is closed, there is an error since faces overlap
    # TODO: Fix closed path handling
    print('generated knot points')

    path = spline(knot_points[:-1])

    print('generated spline')

    faces = create_led_circle_face(
        tube_radius, 
        wall_thickness=wall_thickness, 
        oval_wall_thickness=oval_wall_thickness, 
        orient_to_path=path,
        rotation_z=90)

    print('generated faces')

    result = sweep(faces, path)

    print('swept faces')

    # Render the trefoil knot based on command line arguments
    render_part(result, "Trefoil Knot", args)


if __name__ == "__main__":
    main()
